import { SuggestionInbox } from './SuggestionInbox.mjs';
import { SandboxVerifier } from '../sandbox/SandboxVerifier.mjs';

function candidateFiles(morphResult={}){
  const files=[];
  for(const r of morphResult.results||[]){
    if(r.kind==='ast-project-rewrite') for(const f of r.outputs||[]) files.push({name:f.filename,type:'text/javascript',kind:'code',text:f.code});
    if(r.kind==='convergence-plan' && r.outputHtml) files.push({name:'morph-converged.html',type:'text/html',kind:'website',text:r.outputHtml});
  }
  return files;
}
function describeKinds(result={}) { return [...new Set((result.results||[]).map(r=>r.kind))]; }

export class SuggestionPipeline {
  constructor({engine,inbox,sandbox}={}) {
    if(!engine) throw new Error('SuggestionPipeline requires a MorphEngine');
    this.engine=engine;
    this.inbox=inbox||new SuggestionInbox();
    this.sandbox=sandbox||new SandboxVerifier();
  }
  async propose(inputs, intent={}, meta={}) {
    const result=await this.engine.morph(inputs,intent);
    const files=candidateFiles(result);
    const verification=await this.sandbox.verify(files,{contracts:meta.contracts||{},runtime:meta.runtime!==false,timeoutMs:meta.timeoutMs});
    const kinds=describeKinds(result);
    return this.inbox.submit({
      title:meta.title || (intent.prompt?`Suggested improvement: ${intent.prompt.slice(0,80)}`:'Suggested morph improvement'),
      why:meta.why || `The morph engine detected a candidate change for ${result.plan?.target||'the current project'} while preserving declared invariants.`,
      what:meta.what || `A sandboxed candidate generated by: ${kinds.join(', ')||'morph analysis'}.`,
      does:meta.does || (files.length?`Produces ${files.length} candidate file${files.length===1?'':'s'} without modifying the live project.`:'Records a proposed transformation plan for review.'),
      expectedBenefit:meta.expectedBenefit||'',
      risk:verification.passed?'verified-candidate':'needs-attention',
      scope:meta.scope||files.map(f=>f.name),
      provenance:{source:'morph-engine',mode:result.plan?.mode||intent.mode||'variation',prompt:intent.prompt||'',createdBy:meta.createdBy||'local-automaton'},
      evidence:[{type:'morph-plan',plan:result.plan},{type:'identity',identity:result.identity}],
      verification,
      files
    });
  }
}

export { candidateFiles };
