import { SuggestionInbox } from './SuggestionInbox.mjs';
import { SandboxVerifier } from '../sandbox/SandboxVerifier.mjs';
import { gapSuggestionDraft } from '../graph/GapDetector.mjs';
import { hashString } from '../utils/hash.mjs';

function candidateFiles(morphResult={}){
  const files=[];
  for(const r of morphResult.results||[]){
    if(r.kind==='ast-project-rewrite') for(const f of r.outputs||[]) files.push({name:f.filename,type:'text/javascript',kind:'code',text:f.code});
    if(r.kind==='convergence-plan' && r.outputHtml) files.push({name:'morph-converged.html',type:'text/html',kind:'website',text:r.outputHtml});
  }
  return files;
}
function describeKinds(result={}) { return [...new Set((result.results||[]).map(r=>r.kind))]; }

function bridgeSafe(contract,bridge){ return !!(contract?.supported && bridge?.built && bridge.files?.length); }
function fingerprintAssets(assets=[]){ const rows=assets.map(a=>[a.name||a.filename||'',a.type||'',a.kind||'',typeof a.code==='string'?a.code:(a.text||'')]).sort((a,b)=>String(a[0]).localeCompare(String(b[0]))); return hashString(JSON.stringify(rows)); }
function sameGap(a,b){
  if(!a||!b||a.type!==b.type) return false;
  if(a.type==='unhandled-control'||a.type==='missing-dom-target') return a.selector===b.selector && a.file===b.file;
  if(a.type==='event-without-consumer'||a.type==='consumer-without-producer') return a.event===b.event && a.bus===b.bus;
  if(a.type==='unresolved-import'||a.type==='missing-asset') return a.reference===b.reference && a.file===b.file;
  return a.id===b.id;
}

export class SuggestionPipeline {
  constructor({engine,inbox,sandbox}={}) {
    if(!engine) throw new Error('SuggestionPipeline requires a MorphEngine');
    this.engine=engine;
    this.inbox=inbox||new SuggestionInbox();
    this.sandbox=sandbox||new SandboxVerifier();
  }
  async propose(inputs, intent={}, meta={}) {
    const result=await this.engine.morph(inputs,intent);
    const files=candidateFiles(result);
    const verification=await this.sandbox.verify(files,{contracts:meta.contracts||{},runtime:meta.runtime!==false,timeoutMs:meta.timeoutMs});
    const kinds=describeKinds(result);
    return this.inbox.submit({
      category:'candidate-change', installable:files.length>0,
      title:meta.title || (intent.prompt?`Suggested improvement: ${intent.prompt.slice(0,80)}`:'Suggested morph improvement'),
      why:meta.why || `The morph engine detected a candidate change for ${result.plan?.target||'the current project'} while preserving declared invariants.`,
      what:meta.what || `A sandboxed candidate generated by: ${kinds.join(', ')||'morph analysis'}.`,
      does:meta.does || (files.length?`Produces ${files.length} candidate file${files.length===1?'':'s'} without modifying the live project.`:'Records a proposed transformation plan for review.'),
      expectedBenefit:meta.expectedBenefit||'',
      risk:verification.passed?'verified-candidate':'needs-attention',
      scope:meta.scope||files.map(f=>f.name),
      provenance:{source:'morph-engine',mode:result.plan?.mode||intent.mode||'variation',prompt:intent.prompt||'',createdBy:meta.createdBy||'local-automaton'},
      evidence:[{type:'morph-plan',plan:result.plan},{type:'identity',identity:result.identity},{type:'asset-graph-summary',summary:result.assetGraph},{type:'gap-summary',summary:result.gaps}],
      verification,
      files
    });
  }
  async proposeDetectedGaps(inputs,{minSeverity='medium',includeOrphans=true,createdBy='gap-scout'}={}){
    const diagnosis=await this.engine.diagnose(inputs,{includeOrphans});
    const existing=new Set(this.inbox.list().map(x=>x.provenance?.gapId).filter(Boolean));
    const rank={low:1,medium:2,high:3}, threshold=rank[minSeverity]||1;
    const added=[];
    for(const g of diagnosis.gaps.gaps||[]){
      if((rank[g.severity]||0)<threshold || existing.has(g.id)) continue;
      const draft=gapSuggestionDraft(g); draft.provenance={...draft.provenance,createdBy,projectFingerprint:fingerprintAssets(diagnosis.assets)};
      added.push(this.inbox.submit(draft)); existing.add(g.id);
    }
    return {diagnosis, suggestions:added};
  }
  async buildApprovedGap(inputs, diagnosticSuggestionId, meta={}){
    const diagnostic=this.inbox.get(diagnosticSuggestionId);
    if(!diagnostic) throw new Error(`Unknown diagnostic suggestion: ${diagnosticSuggestionId}`);
    if(diagnostic.status!=='approved') throw new Error(`Gap must be approved for build before bridge construction: ${diagnosticSuggestionId}`);
    if(diagnostic.category!=='gap-diagnostic') throw new Error('Only gap diagnostics can enter the approved-gap bridge builder');
    const gap=diagnostic.evidence?.find(x=>x.type==='gap')?.gap;
    if(!gap) throw new Error('Approved diagnostic has no gap evidence');
    const built=await this.engine.buildBridge(inputs,gap,{includeOrphans:true});
    const currentFingerprint=fingerprintAssets(built.assets);
    if(diagnostic.provenance?.projectFingerprint && diagnostic.provenance.projectFingerprint!==currentFingerprint)
      throw new Error('Project changed after this gap was approved. Re-scan before constructing a fix.');
    const contract=built.contract;
    if(!bridgeSafe(contract,built.bridge)){
      return this.inbox.submit({
        category:'interface-inference',installable:false,parentSuggestionId:diagnostic.id,
        title:`Needs interface decision: ${diagnostic.title}`,
        why:contract?.rationale||'The approved problem could not be mapped to a safe automatic interface.',
        what:`Interface inference for ${gap.type}.`,
        does:'Records the inferred boundary and stops before generating code because confidence or runtime requirements are insufficient.',
        expectedBenefit:'Keep ambiguous self-modification visible instead of guessing.',risk:'manual-review',scope:gap.scope||[],
        provenance:{source:'interface-inference',createdBy:meta.createdBy||'bridge-builder',parentSuggestionId:diagnostic.id,gapId:gap.id},
        evidence:[{type:'gap',gap},{type:'interface-contract',contract}],verification:{passed:true,diagnostic:true,phase:'interface-inference'},files:[]
      });
    }
    const sandboxVerification=await this.sandbox.verify(built.bridge.previewProject,{contracts:meta.contracts||{},runtime:meta.runtime!==false,timeoutMs:meta.timeoutMs});
    const after=await this.engine.diagnose(built.bridge.previewProject,{includeOrphans:true});
    const gapClosed=!(after.gaps.gaps||[]).some(x=>sameGap(gap,x));
    const verification={...sandboxVerification,passed:sandboxVerification.passed&&gapClosed,gapClosure:{passed:gapClosed,gapId:gap.id,remaining:gapClosed?[]:(after.gaps.gaps||[]).filter(x=>sameGap(gap,x))}};
    return this.inbox.submit({
      category:'candidate-bridge',installable:built.bridge.files.length>0,parentSuggestionId:diagnostic.id,
      title:meta.title||`Bridge candidate: ${diagnostic.title}`,
      why:contract.rationale,
      what:`A concrete ${contract.strategy} adapter generated from the approved gap.`,
      does:`Changes ${built.bridge.files.length} project file${built.bridge.files.length===1?'':'s'} to connect the inferred interface.`,
      expectedBenefit:meta.expectedBenefit||'Close the approved project gap while preserving existing project contracts.',
      risk:verification.passed?'verified-candidate':'needs-attention',scope:built.bridge.files.map(f=>f.name),
      provenance:{source:'bridge-builder',createdBy:meta.createdBy||'local-automaton',parentSuggestionId:diagnostic.id,gapId:gap.id,contractId:contract.id,strategy:contract.strategy},
      evidence:[{type:'gap',gap},{type:'interface-contract',contract},{type:'bridge-build',operation:built.bridge.operation,id:built.bridge.id}],
      verification,files:built.bridge.files
    });
  }

}

export { candidateFiles };
