export const GATE_DATA = {
  1:  { name:'The Creative',        circuit:'knowing',       channels:[8],        line:4, color:2, tone:2, base:1, planet:'Sun',     keynote:'Self Expression',  archetype:'The Artist',       semanticCenter:'Identity' },
  2:  { name:'The Receptive',       circuit:'knowing',       channels:[14],       line:2, color:1, tone:1, base:1, planet:'Venus',   keynote:'Higher Knowing',   archetype:'The Navigator',    semanticCenter:'Identity' },
  3:  { name:'Ordering',            circuit:'knowing',       channels:[60],       line:1, color:4, tone:4, base:2, planet:'Mercury', keynote:'Mutation',         archetype:'The Pioneer',      semanticCenter:'Sacral' },
  4:  { name:'Formulization',       circuit:'understanding', channels:[63],       line:3, color:3, tone:3, base:2, planet:'Mercury', keynote:'Answers',          archetype:'The Logician',     semanticCenter:'Ajna' },
  5:  { name:'Fixed Rhythms',       circuit:'understanding', channels:[15],       line:4, color:1, tone:5, base:3, planet:'Saturn',  keynote:'Patience',         archetype:'The Ritualist',    semanticCenter:'Sacral' },
  6:  { name:'Conflict',            circuit:'defense',       channels:[59],       line:6, color:6, tone:6, base:4, planet:'Mars',    keynote:'Intimacy',         archetype:'The Diplomat',     semanticCenter:'Solar Plexus' },
  7:  { name:'Role of Self',        circuit:'understanding', channels:[31],       line:1, color:5, tone:1, base:3, planet:'Venus',   keynote:'Interaction',      archetype:'The Conductor',    semanticCenter:'Identity' },
  8:  { name:'Contribution',        circuit:'knowing',       channels:[1],        line:4, color:4, tone:2, base:1, planet:'Mercury', keynote:'Contribution',     archetype:'The Broadcaster',  semanticCenter:'Throat' },
  9:  { name:'Focus',               circuit:'understanding', channels:[52],       line:2, color:2, tone:2, base:2, planet:'Venus',   keynote:'Determination',    archetype:'The Focuser',      semanticCenter:'Sacral' },
  10: { name:'Behavior of Self',    circuit:'integration',   channels:[20,34,57], line:4, color:6, tone:6, base:5, planet:'Pluto',   keynote:'Love of Life',     archetype:'The Nomad',        semanticCenter:'Identity' },
  11: { name:'Ideas',               circuit:'sensing',       channels:[56],       line:4, color:3, tone:3, base:2, planet:'Jupiter', keynote:'Harmony',          archetype:'The Idealist',     semanticCenter:'Ajna' },
  12: { name:'Caution',             circuit:'knowing',       channels:[22],       line:2, color:5, tone:5, base:4, planet:'Earth',   keynote:'Caution',          archetype:'The Hermit',       semanticCenter:'Throat' },
  13: { name:'The Listener',        circuit:'sensing',       channels:[33],       line:5, color:1, tone:1, base:1, planet:'Sun',     keynote:'Listening',        archetype:'The Witness',      semanticCenter:'Identity' },
  14: { name:'Power Skills',        circuit:'knowing',       channels:[2],        line:3, color:2, tone:3, base:2, planet:'Mars',    keynote:'Possession',       archetype:'The Keeper',       semanticCenter:'Sacral' },
  15: { name:'Extremes',            circuit:'understanding', channels:[5],        line:2, color:4, tone:4, base:3, planet:'Jupiter', keynote:'Humanity',         archetype:'The Humanitarian', semanticCenter:'Identity' },
  16: { name:'Skills',              circuit:'understanding', channels:[48],       line:5, color:5, tone:5, base:4, planet:'Mercury', keynote:'Enthusiasm',       archetype:'The Talent',       semanticCenter:'Throat' },
  17: { name:'Opinions',            circuit:'understanding', channels:[62],       line:1, color:6, tone:6, base:5, planet:'Neptune', keynote:'Opinions',         archetype:'The Organizer',    semanticCenter:'Ajna' },
  18: { name:'Correction',          circuit:'understanding', channels:[58],       line:4, color:1, tone:1, base:1, planet:'Pluto',   keynote:'Judgment',         archetype:'The Editor',       semanticCenter:'Spleen' },
  19: { name:'Wanting',             circuit:'defense',       channels:[49],       line:2, color:2, tone:2, base:2, planet:'Earth',   keynote:'Sensitivity',      archetype:'The Sensitive',    semanticCenter:'Root' },
  20: { name:'The Now',             circuit:'integration',   channels:[10,34,57], line:3, color:3, tone:3, base:2, planet:'Moon',    keynote:'Contemplation',    archetype:'The Presence',     semanticCenter:'Throat' },
  21: { name:'The Hunter',          circuit:'ego',           channels:[45],       line:5, color:4, tone:4, base:3, planet:'Mars',    keynote:'Control',          archetype:'The Controller',   semanticCenter:'Ego' },
  22: { name:'Openness',            circuit:'knowing',       channels:[12],       line:1, color:5, tone:5, base:4, planet:'Venus',   keynote:'Grace',            archetype:'The Socialite',    semanticCenter:'Solar Plexus' },
  23: { name:'Assimilation',        circuit:'knowing',       channels:[43],       line:4, color:6, tone:6, base:5, planet:'Uranus',  keynote:'Assimilation',     archetype:'The Transmitter',  semanticCenter:'Throat' },
  24: { name:'Rationalization',     circuit:'knowing',       channels:[61],       line:4, color:1, tone:1, base:1, planet:'Uranus',  keynote:'Return',           archetype:'The Thinker',      semanticCenter:'Ajna' },
  25: { name:'Spirit of Self',      circuit:'integration',   channels:[51],       line:2, color:2, tone:2, base:2, planet:'Uranus',  keynote:'Innocence',        archetype:'The Shaman',       semanticCenter:'Identity' },
  26: { name:'The Egoist',          circuit:'ego',           channels:[44],       line:3, color:3, tone:3, base:2, planet:'Mars',    keynote:'Egotism',          archetype:'The Salesperson',  semanticCenter:'Ego' },
  27: { name:'Caring',              circuit:'defense',       channels:[50],       line:4, color:4, tone:4, base:3, planet:'Venus',   keynote:'Nourishment',      archetype:'The Caretaker',    semanticCenter:'Sacral' },
  28: { name:'Game Player',         circuit:'knowing',       channels:[38],       line:5, color:5, tone:5, base:4, planet:'Pluto',   keynote:'Struggle',         archetype:'The Gambler',      semanticCenter:'Spleen' },
  29: { name:'Saying Yes',          circuit:'sensing',       channels:[46],       line:2, color:6, tone:6, base:5, planet:'Earth',   keynote:'Devotion',         archetype:'The Devotee',      semanticCenter:'Sacral' },
  30: { name:'Feelings',            circuit:'sensing',       channels:[41],       line:3, color:1, tone:1, base:1, planet:'Pluto',   keynote:'Desire',           archetype:'The Dreamer',      semanticCenter:'Solar Plexus' },
  31: { name:'Leadership',          circuit:'understanding', channels:[7],        line:4, color:2, tone:2, base:2, planet:'Sun',     keynote:'Leadership',       archetype:'The Leader',       semanticCenter:'Throat' },
  32: { name:'Continuity',          circuit:'ego',           channels:[54],       line:5, color:3, tone:3, base:2, planet:'Saturn',  keynote:'Continuity',       archetype:'The Preserver',    semanticCenter:'Spleen' },
  33: { name:'Privacy',             circuit:'sensing',       channels:[13],       line:1, color:4, tone:4, base:3, planet:'Mercury', keynote:'Retreat',          archetype:'The Monk',         semanticCenter:'Throat' },
  34: { name:'Power',               circuit:'integration',   channels:[10,20,57], line:3, color:5, tone:5, base:4, planet:'Uranus',  keynote:'Power',            archetype:'The Force',        semanticCenter:'Sacral' },
  35: { name:'Change',              circuit:'sensing',       channels:[36],       line:2, color:6, tone:6, base:5, planet:'Venus',   keynote:'Change',           archetype:'The Adventurer',   semanticCenter:'Throat' },
  36: { name:'Crisis',              circuit:'sensing',       channels:[35],       line:1, color:1, tone:1, base:1, planet:'Mars',    keynote:'Darkening',        archetype:'The Crisis Agent', semanticCenter:'Solar Plexus' },
  37: { name:'Friendship',          circuit:'ego',           channels:[40],       line:4, color:2, tone:2, base:2, planet:'Moon',    keynote:'Friendship',       archetype:'The Friend',       semanticCenter:'Solar Plexus' },
  38: { name:'The Fighter',         circuit:'knowing',       channels:[28],       line:5, color:3, tone:3, base:2, planet:'Pluto',   keynote:'Opposition',       archetype:'The Warrior',      semanticCenter:'Root' },
  39: { name:'Provocation',         circuit:'knowing',       channels:[55],       line:2, color:4, tone:4, base:3, planet:'Pluto',   keynote:'Obstruction',      archetype:'The Provocateur',  semanticCenter:'Root' },
  40: { name:'Aloneness',           circuit:'ego',           channels:[37],       line:3, color:5, tone:5, base:4, planet:'Earth',   keynote:'Deliverance',      archetype:'The Lone Wolf',    semanticCenter:'Ego' },
  41: { name:'Contraction',         circuit:'sensing',       channels:[30],       line:4, color:6, tone:6, base:5, planet:'Sun',     keynote:'Imagination',      archetype:'The Initiator',    semanticCenter:'Root' },
  42: { name:'Growth',              circuit:'sensing',       channels:[53],       line:1, color:1, tone:1, base:1, planet:'Earth',   keynote:'Growth',           archetype:'The Grower',       semanticCenter:'Sacral' },
  43: { name:'Insight',             circuit:'knowing',       channels:[23],       line:4, color:2, tone:2, base:2, planet:'Uranus',  keynote:'Insight',          archetype:'The Genius',       semanticCenter:'Ajna' },
  44: { name:'Patterns',            circuit:'ego',           channels:[26],       line:5, color:3, tone:3, base:2, planet:'Pluto',   keynote:'Alertness',        archetype:'The Tracker',      semanticCenter:'Spleen' },
  45: { name:'The Gatherer',        circuit:'ego',           channels:[21],       line:2, color:4, tone:4, base:3, planet:'Venus',   keynote:'Gathering',        archetype:'The King/Queen',   semanticCenter:'Throat' },
  46: { name:'Determination',       circuit:'sensing',       channels:[29],       line:3, color:5, tone:5, base:4, planet:'Venus',   keynote:'Discovery',        archetype:'The Lucky One',    semanticCenter:'Identity' },
  47: { name:'Realization',         circuit:'sensing',       channels:[64],       line:4, color:6, tone:6, base:5, planet:'Saturn',  keynote:'Oppression',       archetype:'The Transformer',  semanticCenter:'Ajna' },
  48: { name:'Depth',               circuit:'understanding', channels:[16],       line:1, color:1, tone:1, base:1, planet:'Neptune', keynote:'The Well',         archetype:'The Specialist',   semanticCenter:'Spleen' },
  49: { name:'Principles',          circuit:'defense',       channels:[19],       line:2, color:2, tone:2, base:2, planet:'Venus',   keynote:'Principles',       archetype:'The Revolutionary',semanticCenter:'Solar Plexus' },
  50: { name:'Values',              circuit:'defense',       channels:[27],       line:3, color:3, tone:3, base:2, planet:'Pluto',   keynote:'Values',           archetype:'The Judge',        semanticCenter:'Spleen' },
  51: { name:'Shock',               circuit:'integration',   channels:[25],       line:4, color:4, tone:4, base:3, planet:'Mars',    keynote:'Shock',            archetype:'The Competitor',   semanticCenter:'Ego' },
  52: { name:'Stillness',           circuit:'understanding', channels:[9],        line:5, color:5, tone:5, base:4, planet:'Earth',   keynote:'Stillness',        archetype:'The Meditator',    semanticCenter:'Root' },
  53: { name:'Beginnings',          circuit:'sensing',       channels:[42],       line:2, color:6, tone:6, base:5, planet:'Earth',   keynote:'Development',      archetype:'The Starter',      semanticCenter:'Root' },
  54: { name:'Ambition',            circuit:'ego',           channels:[32],       line:3, color:1, tone:1, base:1, planet:'Jupiter', keynote:'Transformation',   archetype:'The Climber',      semanticCenter:'Root' },
  55: { name:'Abundance',           circuit:'knowing',       channels:[39],       line:4, color:2, tone:2, base:2, planet:'Saturn',  keynote:'Abundance',        archetype:'The Mystic',       semanticCenter:'Solar Plexus' },
  56: { name:'Stimulation',         circuit:'sensing',       channels:[11],       line:5, color:3, tone:3, base:2, planet:'Mercury', keynote:'Wandering',        archetype:'The Storyteller',  semanticCenter:'Throat' },
  57: { name:'The Intuitive',       circuit:'integration',   channels:[10,20,34], line:2, color:4, tone:4, base:3, planet:'Moon',    keynote:'Intuition',        archetype:'The Psychic',      semanticCenter:'Spleen' },
  58: { name:'Vitality',            circuit:'understanding', channels:[18],       line:3, color:5, tone:5, base:4, planet:'Saturn',  keynote:'Joy',              archetype:'The Athlete',      semanticCenter:'Root' },
  59: { name:'Sexuality',           circuit:'defense',       channels:[6],        line:4, color:6, tone:6, base:5, planet:'Venus',   keynote:'Sexuality',        archetype:'The Seducer',      semanticCenter:'Sacral' },
  60: { name:'Acceptance',          circuit:'knowing',       channels:[3],        line:5, color:1, tone:1, base:1, planet:'Saturn',  keynote:'Limitation',       archetype:'The Gatekeeper',   semanticCenter:'Root' },
  61: { name:'Inner Truth',         circuit:'knowing',       channels:[24],       line:2, color:2, tone:2, base:2, planet:'Neptune', keynote:'Mystery',          archetype:'The Mystic',       semanticCenter:'Crown' },
  62: { name:'Details',             circuit:'understanding', channels:[17],       line:3, color:3, tone:3, base:2, planet:'Earth',   keynote:'Detail',           archetype:'The Analyst',      semanticCenter:'Throat' },
  63: { name:'Doubt',               circuit:'understanding', channels:[4],        line:4, color:4, tone:4, base:3, planet:'Neptune', keynote:'Logic',            archetype:'The Doubter',      semanticCenter:'Crown' },
  64: { name:'Confusion',           circuit:'sensing',       channels:[47],       line:5, color:5, tone:5, base:4, planet:'Pluto',   keynote:'Confusion',        archetype:'The Visionary',    semanticCenter:'Crown' },
};

export function gateContent(gateNumber) {
  const entry = GATE_DATA[gateNumber];
  if (!entry) return null;
  return Object.freeze({ gate: gateNumber, ...entry });
}
